//
// auto-generated by ops.py on 2014-07-10 10:37
//

#include "./MPI_OpenMP_XeonPhi/clover_leaf_common.h"

int xdim0_calc_dt_kernel_min;

#define OPS_ACC0(x,y) (x+xdim0_calc_dt_kernel_min*(y))

//user function
inline 
void calc_dt_kernel_min(const double* dt_min ,
                    double* dt_min_val) {
  *dt_min_val = MIN(*dt_min_val, dt_min[OPS_ACC0(0,0)]);

}



#undef OPS_ACC0


void calc_dt_kernel_min_c_wrapper(
  double *p_a0,
  double *p_a1,
  int x_size, int y_size) {
  double p_a1_l = *p_a1;
  #pragma omp parallel for reduction(min:p_a1_l)
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      calc_dt_kernel_min(  p_a0 + n_x*1 + n_y*xdim0_calc_dt_kernel_min*1,
           &p_a1_l );

    }
  }
  *p_a1 = p_a1_l;
}
